version: '3.7'

volumes:
  grafana-storage:
    driver: local

networks:
  grafana-network:
    driver: bridge

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      # - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      # - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./dashboards:/var/lib/grafana/dashboards
      - ./datasources:/etc/grafana/datasources
      - ./plugins:/var/lib/grafana/plugins
      - ./provisioning:/etc/grafana/provisionin
    ports:
      - 3000:3000
    networks: 
      - grafana-network
